config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
	root 'institutions#index'
  devise_for :users
  resources :dishes
  resources :institutions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter

  def authorized?(action, subject = nil)
    user.admin?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
	belongs_to :institution
end

app/models/institution.rb
class Institution < ApplicationRecord
	has_many :dishs, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?


	def access_denied(exception)
		flash[:danger] = exception.message
		redirect_to root_url
	end

	private


	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:account_update, keys: [:name])
	end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: 'Dish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.require(:dish).permit(:title, :price, :description)
    end
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :set_institution, only: [:show, :edit, :update, :destroy]

  # GET /institutions
  # GET /institutions.json
  def index
    @institutions = Institution.all
  end

  # GET /institutions/1
  # GET /institutions/1.json
  def show
  end

  # GET /institutions/new
  def new
    @institution = Institution.new
  end

  # GET /institutions/1/edit
  def edit
  end

  # POST /institutions
  # POST /institutions.json
  def create
    @institution = Institution.new(institution_params)

    respond_to do |format|
      if @institution.save
        format.html { redirect_to @institution, notice: 'Institution was successfully created.' }
        format.json { render :show, status: :created, location: @institution }
      else
        format.html { render :new }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institutions/1
  # PATCH/PUT /institutions/1.json
  def update
    respond_to do |format|
      if @institution.update(institution_params)
        format.html { redirect_to @institution, notice: 'Institution was successfully updated.' }
        format.json { render :show, status: :ok, location: @institution }
      else
        format.html { render :edit }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1
  # DELETE /institutions/1.json
  def destroy
    @institution.destroy
    respond_to do |format|
      format.html { redirect_to institutions_url, notice: 'Institution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institution
      @institution = Institution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institution_params
      params.require(:institution).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/dishes/_form.html.erb
<%= form_with(model: dish, local: true) do |form| %>
  <% if dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% dish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :institutions %>
    <%= form.collection_select :institution_id, Institution.all.order(title: "asc"), :id, :title, { prompt: true } %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing Dish</h1>

<%= render 'form', dish: @dish %>

<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path %>

app/views/dishes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dishes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dishes.each do |dish| %>
      <tr>
        <td><%= dish.title %></td>
        <td><%= dish.price %></td>
        <td><%= dish.description %></td>
        <td><%= link_to 'Show', dish %></td>
        <td><%= link_to 'Edit', edit_dish_path(dish) %></td>
        <td><%= link_to 'Destroy', dish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dish', new_dish_path %>

app/views/dishes/new.html.erb
<h1>New Dish</h1>

<%= render 'form', dish: @dish %>

<%= link_to 'Back', dishes_path %>

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @dish.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @dish.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @dish.description %>
</p>

<%= link_to 'Edit', edit_dish_path(@dish) %> |
<%= link_to 'Back', dishes_path %>

app/views/institutions/_form.html.erb
<%= form_with(model: institution, local: true) do |form| %>
  <% if institution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(institution.errors.count, "error") %> prohibited this institution from being saved:</h2>

      <ul>
      <% institution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mt-5">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/institutions/edit.html.erb
<h1>Editing Institution</h1>

<%= render 'form', institution: @institution %>

<%= link_to 'Show', @institution %> |
<%= link_to 'Back', institutions_path %>

app/views/institutions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Institutions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="table">
    <% @institutions.each do |institution| %>
      <tr>
        <td><%= institution.title %></td>
        <td><%= institution.description %></td>
        <td><%= link_to 'Show', institution %></td>
        <td><%= link_to 'Edit', edit_institution_path(institution) %></td>
        <td><%= link_to 'Destroy', institution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Institution', new_institution_path %>

app/views/institutions/new.html.erb
<h1>New Institution</h1>

<%= render 'form', institution: @institution %>

<%= link_to 'Back', institutions_path %>

app/views/institutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @institution.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @institution.description %>
</p>

<%= link_to 'Edit', edit_institution_path(@institution) %> |
<%= link_to 'Back', institutions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Laba</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="container mt-3">
  <nav class="navbar fixed-top navbar-dark bg-dark navbar-expand-md">
    <div class="container">
      <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        &#x2630;
      </button>

      <%= link_to 'Institutions', root_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <%= link_to 'Dishes', dishes_path, class: 'nav-link nav-item' %>
          
        </ul>
        <div class="navbar-nav ml-auto">
          <div class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <div class="nav-item">
              <span class="navbar-text">
                Hello, &nbsp;
                <span>
                </div>

                <div class="dropdown show">
                  <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'btn btn-secondary dropdown-toggle', 'role' => "button", 'id' => "dropdownMenuLink", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false" %>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <%= link_to 'Edit profile', edit_user_registration_path(current_user), class: 'dropdown-item' %>
                    <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
                  </div>
                  <div>
                    <% else %>
                    <div class="nav-item">
                      <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
                    </div>
                    <div class="nav-item">
                      <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
                    </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </nav>
          <%= yield %>
        </body>
        </html>